### ISSUE TITLE
Продукты только по-одному можно покупать?

### ISSUE THREAD

**Issue by coursar** [powerlord1990/HW6.1-DB#5]

**Comment by powerlord1990** [comment]
Нет я ввел переменную number которая указывает на количество покупаемого товара

**Comment by coursar** [comment]
Я про то, могу ли я одновременно купить два разных продукта? Если да, то как это можно будет увидеть (что я одновременно купил два разных)?

**Comment by powerlord1990** [comment]
исправил ввел новую таблицу. в заказах будет выделяться кто заказал, общая стоимость и статус заказа. во второй будет содержимое конкретного заказа
